version: '3'

services:
  mongodb-service:
    hostname: mongodb
    container_name: mongodb-srv
    image: mongo
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
